# This file creates an intermediate cert for issuing client certificates,
# and assumes that a root CA issuer has already been configured in the
# cert-manager namespace
#
# See root_issuer_dev.yaml  for creating a dev root
# See root_issuer_prod.yaml for creating a production root from a known secret

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: print-your-cert-ca
  namespace: cert-manager
spec:
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: print-your-cert-ca
  commonName: The cert-manager maintainers
  subject:
    organizations:
    - CNCF
    organizationalUnits:
    - cert-manager
    countries: # Change for the country you're issuing in!
    - GB
    localities: # Change for the city you're issuing in!
    - London
  duration: 438000h # 50 years.
  issuerRef:
    name: root-print-your-cert-ca-issuer
    kind: Issuer

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: print-your-cert-ca
  namespace: cert-manager
spec:
  ca:
    secretName: print-your-cert-ca
