FROM alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

ARG $TARGETARCH

WORKDIR /root

RUN apk add --update --no-cache python3 py3-pillow py3-future py3-jinja2 py3-bottle py3-pip py3-usb imagemagick ttf-opensans libqrencode-tools step-cli openssl bash curl libusb fontconfig ttf-dejavu jq kubectl timg \
    && python3 -m venv /venv && . /venv/bin/activate \
    && pip3 install --no-cache-dir --upgrade brother_ql \
    && curl -sSL https://github.com/pklaus/brother_ql_web/archive/refs/heads/master.tar.gz | tar xz -C /root \
    && cd /root/brother_ql_web-master \
    && pip3 --no-cache-dir install -r requirements.txt \
    && printf '#!/bin/sh\ncd /root/brother_ql_web-master && exec python3 ./brother_ql_web.py "$@"\n' >/usr/local/bin/brother_ql_web \
    && chmod +x /usr/local/bin/brother_ql_web

COPY config.json *.png /root/
COPY cert-card print-your-cert-controller /usr/local/bin/

EXPOSE 8013

CMD [ "sh", "-c", ". /venv/bin/activate && exec print-your-cert-controller" ]
