FROM alpine:edge@sha256:115729ec5cb049ba6359c3ab005ac742012d92bbaa5b8bc1a878f1e8f62c0cb8
ARG TARGETARCH
COPY print-your-cert-ui-$TARGETARCH /usr/local/bin/print-your-cert-ui
ENTRYPOINT ["print-your-cert-ui"]
