FROM alpine:edge@sha256:ea71a031ed91cd46b00d438876550bc765da43b4ae40f331a12daf62f0937758
ARG TARGETARCH
COPY print-your-cert-ui-$TARGETARCH /usr/local/bin/print-your-cert-ui
ENTRYPOINT ["print-your-cert-ui"]
