#! /usr/bin/env bash

# entr bash -c "./pem-to-png <foo.crt" <<<$'pem-to-png\n'

set -euo pipefail

echo "Reading PEM from stdin..." >&2
cat >/tmp/crt

cat <<EOF >/tmp/pem-to-png.txt

Thank you for visiting the cert-manager
booth! We hope you are enjoying
your time in Valencia.

This card is a proof that you
were there! on the back of
the card, the QR code
contains your certificate.
EOF

# When printing to the Brother QL-820WNB, the width of the image (as opposed to
# the height) is scaled to the 6.2 cm of the label tape's width. In the
# following, e.g., 984 x 696 px, means height x width. So the "second" number is
# the one scaled to 6.2 cm.
#
#  Format 0: 696 px x 696 px (6.2 x 6.2 cm)
#  Format 1: 984 x 696  px (8.7 x 6.2 cm, requires --rotate 90 because the image
#            comes at 696 x 984 px)
#  Format 2: 696 x 696 px 6.2 cm 492 px = 4.4 cm ()

# brother_ql must be used with "--rotate 90".
convert -size 984x696 canvas:white \
    \( -gravity NorthEast kubecon-eu-2022-logo.svg -resize 400x400 -background white -alpha remove -alpha off -monochrome \) -geometry +0+0 -composite \
    \( -gravity NorthEast logo.svg -resize 370x370 -background white -alpha remove -alpha off -monochrome \) -geometry +20+190 -composite \
    \( -gravity NorthWest -font Open-Sans -pointsize 30 -fill black -annotate +0-40 "@/tmp/pem-to-png.txt" \) -geometry +0+0 \
    \( -gravity SouthWest -font DejaVu-Sans-Mono -pointsize 26 -fill black -annotate +0+0 "$(step certificate inspect --short /tmp/crt | sed -e 's/\[\(.*\)\]/\n\1/' -e 's/Certificate (\(.*\))/Certificate\nAlgorithm: \1/' | sed 's/^  //')" \) -geometry +0+0 \
    -background None -layers Flatten front.png

qrencode --type PNG --margin 0 -o - </tmp/crt | convert - -monochrome -filter point -interpolate nearest -resize 696x696 back.png
